Ruby on Rails capstone project Budget app pull request
theresetuyi/Budget-app-Ruby-on-Rails-capstone-project pull request #1
Opened 2023-09-14 11:43 UTC by theresetuyi

## Ruby on Rails capstone project Budget app

- se ruby gems as software packages system.
- Install Ruby on Rails framework.
- Understand Rails RESTful design and router.
- Use controllers to handle requests and render empty views.
- Use params from browser request in a safe way.
- Use preprocessed html file with embedded Ruby code.
- Use layouts and templates for shared content.
- Use database migration files to maintain database schema.
- Use validations for models.
- Secure app from n+1 problems.
- Understand what ORM is.
- Write SQL queries with ActiveRecord.
- Set up associations between models.
- Build a webapp that requires the user to log in.
- Use devise gem for authentication.
- Limit access to webapp resources based on authorization rules.
- Analyze in writing why you have made a coding choice using one structure over another.

2023-09-14 23:11 UTC, Lucas-Masaba requested changes
# Hello @theresetuyi  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Met most requirements :gear: 
- Descriptive README :scroll: 
- Written tests passing :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 23:11 UTC, Lucas-Masaba commented on README.md
> +- [Loomlink] (https://www.loom.com/share/04fc614fdd524fcd96484b2e41ab7100)
- [ ] In the video you recorded, you did not mention a piece of code that you found interesting or that you are proud of making. Please add this to your video.

2023-09-14 23:11 UTC, Lucas-Masaba commented on spec/integration/categories_spec.rb
> +require 'rails_helper'
- [ ] Please add some more integration tests fo the other controllers. here I only see that of the categories controller.

2023-09-15 21:37 UTC, DeliceLydia approved these changes
## Hi @theresetuyi, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


### Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-09-15 22:04 UTC, merged